package com.bobo.greendao;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ITEM".
 */
@Entity
public class Item {

    @Id
    private Long id;
    private String type;
    private String title;
    private String url;
    private String des;

    @Generated(hash = 1470900980)
    public Item() {
    }

    public Item(Long id) {
        this.id = id;
    }

    @Generated(hash = 546600048)
    public Item(Long id, String type, String title, String url, String des) {
        this.id = id;
        this.type = type;
        this.title = title;
        this.url = url;
        this.des = des;
    }

    public Long getId() {
        return id;
    }

    public void setId() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((des == null) ? 0 : des.hashCode());
        result = prime * result + ((title == null) ? 0 : title.hashCode());
        result = prime * result + ((type == null) ? 0 : type.hashCode());
        result = prime * result + ((url == null) ? 0 : url.hashCode());
        id  = (long)result;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDes() {
        return des;
    }

    public void setDes(String des) {
        this.des = des;
    }

    public void setId(Long id) {
        this.id = id;
    }



}
